project:
  type: website

website:
  title: "Off-Season"
  navbar:
    background: primary
    logo: "images/GlasgowLogoOutline.png"
    collapse: true
    pinned: true
    left:
      - text: Getting Started
        menu:
          - href: building.qmd
            text: Building The Ultimate Athlete
          - href: goals.qmd
            text: Setting Personal Goals
          - href: planning.qmd
            text: Planning Your Season
      - text: Athletic Development
        menu:
          - href: strength.qmd
            text: Strength Training
          - href: mobility.qmd
            text: Mobility Training
          - href: endurance.qmd
            text: Endurance Training
          - href: saq.qmd
            text: Speed, Agility, Quickness
          - href: recovery.qmd
            text: Recovery
          - href: injury.qmd
            text: Injury Prevention And Rehab
      - text: Skill Development
        menu:
          - href: skills.qmd
            text: Skill Development In Ultimate
          - href: throwing_practice.qmd
            text: How To Practice Your Throwing Drills
          - href: drill_tips.qmd
            text: 30 Tips For Throwing Drills
      - text: Peak Performance
        menu:
          - href: nutrition.qmd
            text: Nutrition
          - href: mental.qmd
            text: Mind Games
          - href: video.qmd
            text: Watch And Learn
          - href: trials.qmd
            text: Preparing For Trials

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: true

editor: visual

