---
title: "30 Tips For Throwing Drills"
---

Improving your throwing skills requires focused, dedicated practice. Whether you are warming up for training or taking part in a dedicated skills session, make sure you are getting optimal benefit from your reps. Here are some tips for getting the most out of your throwing drills.

#### **Technique first**

Nail the technique first, before you add defense, before you try to throw hard, before you over complicate your drills, get the technique down. **Get feedback** from a coach, teammate or video analysis.

#### **Repetition**

By repeating a similar task multiple times we develop **muscle memory**. Making multiple throws in quick succession allows us to replicate good technique and correct poor form. Drilling with a constant supply of discs is ideal when working on technique. Be sure to rest regularly to avoid loss of form through lack of focus or fatigue.

#### **Add variation**

Once your technique is sound, play around with varying certain elements of your drills to develop your skills.

#### **Be specific**

It’s not just a backhand. Be specific about the perfect pass, the shape of the throw, the game scenario and the target you want to hit.

#### **Visualise - Execute - Evaluate**

Visualise a specific throw. Execute without over-thinking. Evaluate the result.

#### **Don’t over-think it**

Consciously thinking about individual body parts can be distracting and overwhelming. Give yourself feedback with verbs and adverbs: “Faster, more flick, smoother, pivot wider etc”

#### **Visualise game scenarios**

Imagine a situation where you would use the throw you are drilling in a game. Visualise the direction of play, the sideline, your team mates, defender positioning etc. This will help you to maintain focus in drills and apply the skills during play.

#### **Exaggeration**

Exaggerating skills can be a useful method to gain control and range of technique. For instance, if you naturally tend to throw with roll-curve and can’t get the hang of inside-out, try throwing high, loopy, sharp IO angled backhands to begin with.

#### **Use your time effectively**

If you think 90% of your on field throws will be forehand or backhand then spend the most time perfecting these throws.

#### **Research and development**

Devote some time to working on new throws or changes in technique. Keep working on technique in your throwing sessions until you are comfortable to use it in drills. You’ll then find it will naturally creep into your game. It’s also fun to play around with some new throws at the end of a session to wind down.

#### **Catching practice**

Throwing drills are generally catching drills as well, don’t be lazy with your catching technique.

#### **Throw to targets**

Whether it’s a set of cones or a receiver, give yourself a small target to aim for. Receivers can raise their hands as targets to improve accuracy, think about where you want the player to catch the disc (left side, chest, right side, high). Passes in matches often have a large margin for error as we are throwing to running receivers that can change their speed and direction. Developing accuracy therefore requires deliberate and focused throwing practice.

#### **Use props**

Trees and cones can make good targets (disc golf) and good forces to throw around.

#### **Maintain focus and intensity**

Don’t let a dropped disc disturb the pace of a drill.

#### **Throw when it’s windy**

The wind offers resistance and highlights flaws in your technique. If you can learn to throw in the wind you’ll be amazed at what you can do on a still day. As well as throwing through the wind, learn to use it to get your disc to the intended target.

#### **Rotate your drills**

Change up the wind direction and learn to throw in different winds.

#### **Throw to moving targets**

In games we throw to moving targets more often than stationary ones. Think about the types of cuts you would make in a game.

#### **Practice moving into a throw**

In games we often receive the disc from one direction, then turn and throw in another direction. We also receive the disc on the move. Try to replicate these movements in some of your drills.

#### **3 \> 2**

Throwing in pairs is fine and will give you lots of reps, but a 3rd person can add defense, continuation throws or multiple throwing options to your drills, making them more game-like.

#### **Use multiple discs**

Increase your reps and time between reps by using a stack of discs or having multiple discs in the air at once. 

#### **Play defense**

Play defense at a challenging level for the offense players so they get the most out of drills.

#### **Reactive or random drills**

Add a reactive or random element to drills to force the thrower to think and execute quickly.

#### **Versatility**

Good throwers have many tools at their disposal and can use multiple throws in the same situation. Use different throws in drills to hit the same targets.

#### **Play small sided games**

Small sided games are a great way to get lots of realistic, randomised throwing reps. Make sure you have a focus and think about applying conditions or scenarios to the game to aid your learning.

#### **Challenge yourself**

Improve by working at the limits of your ability and trying to push beyond. If you are throwing long, set a cone to aim for that is just beyond a comfortable distance for you. If you are working on wide pivots try [this drill](https://www.youtube.com/watch?v=KdRIBL0Lh0w).

#### **Be okay with making mistakes**

Deliberate practice occurs outside of your comfort zone. It should be difficult, don’t beat yourself up when you make errors. Try to remain in a state of relaxed concentration.

#### **Scale the difficulty**

If a drill is too difficult for you to complete then think of ways to scale down the difficulty. Remove one of the variables or ask the defense to be less active. 

#### **Consistency**

Consistency and accuracy should be a prime focus. Skill development isn’t all about new techniques and throwing further. Consistently executing the throws you already have will make you an effective and reliable player. This is especially important in the lead up to tournaments where you want to feel confident hitting low risk options.

#### **Take a break**

Focused, deliberate practice can be physically and mentally draining. When your concentration or form dips, take a break. Increasing your focused time over multiple sessions can help build your mental toughness.

#### **Cross training**

A lot of athletic and coordination skills are transferable across sports. Don’t feel like you always need to play ultimate to work on your skills. Basketball and volleyball are great for jumping technique; Spikeball requires quick reactions and the occasional layout; a round of disc golf can give you new insights on your throwing technique.
