---
title: "Mind Games"
---

### Mental resilience and why we need it

Playing at a high level requires more than solid fitness, skills and knowledge. We also need **mental resilience** to be able to utilise these consistently, regardless of external factors or outcomes.

Building up mental resilience takes intentionality, time and practice, but will benefit us hugely when playing sport and in the rest of our lives too.

### Perspective and expectations: Winning vs competing

Our default state coming into a game is losing the game - if we don't turn up, we've lost. 

If we turn up and choose to **fight**, we **could** win. 

If we don't win, that's okay. It's not a negative thing - we’re no worse off than how we started.

\

But, if we play Ultimate purely to win, we’re going to be disappointed. 

Winning is a reflection of lots of things, not just our personal performance:

-   The performance of our teammates

-   The weather, especially wind or rain

-   The other team’s performance

-   The surface

-   Who wins the toss etc. etc.

\

Winning feels good! And it can give us confidence moving forward. Some teams, like Clapham, are expected to win and this expectation sets the standard which can drive them to perform well. However, it’s not helpful to fixate on winning or even the scoreline during a game. This can create an atmosphere of tension and fear as every wrong move jeopardises our chances of winning. Teams can give way to individualism and comparison. Mistakes can feel like a huge deal. Frustration and pressure can build. Worse, a team who believes they’re entitled to win finds no joy in competing because they “should” win anyway. Losing for them may not just be disappointing, it could be humiliating.

Sounds pretty grim, right?\\

\

Sometimes winning is simply out of our control. Sometimes the opposition is just better. 

\

What if, instead, we were driven by a desire to **compete**?

\

In this state, we’ve accepted we **could** lose and the fear reduces. 

If we don’t try, we’ll lose anyway. So why not **fight** and see what happens?

\

Playing to **compete** allows you to:

-   **Relish tight match-ups**, knowing it’s bringing out your best and stretching you. 

-   **Build team chemistry and culture**: players give 100%, they give each other space to do their bit, cheer each other on.

-   **Builds a more mentally resilient team**: you stay and fight, keep pushing, no matter what the circumstances. 

-   **Stay in the present moment**, playing one point at a time, rather than racing ahead to think about the consequences of the scoreline.

\

Let's take **should** and throw it in the bin. And replace it with **can** and **could**.

Instead of entitlement, individualism and ego-driven expectations, let’s make it about **possibility** and **opportunity**.

\

**TASK**: Check in before each match and training session. Are you fixated on winning? Why? Or are you fired up and ready to **compete**, playing your part to the best of your ability, and doing all your can to help the team fight and work hard? If needed, what can you do to switch your focus?

\

**EXTRA**: Expectations of ourselves

Often frustration comes when we fall short of our own expectations for ourselves. But are your expectations realistic or are you accidentally setting a standard for yourself you don’t yet have the skills or knowledge to reach? It’s important to have an honest and realistic view of ourselves and our role on a team in order to hold yourself to a realistic standard. Coaches and experienced teammates can help us see things more clearly and help keep us on track.\

### Managing our emotions: Apathetic or angry vs fueled and focused

Emotions are:

-   **naturally heightened in sport**, especially when your body is working hard and you care deeply about what you’re doing.

-   **Valid**! And a reaction to what you perceive is happening around you, seen through a filter of how you feel about yourself and others. Your body is pretty clever and wants to tell you what’s happening. But we need to interpret and handle them with care.

-   **Infectious**. In Ultimate, we’re also helping manage the atmosphere of our team so we need to look out for ourselves whilst also caring for / not hurting others.

-   **Necessary**. We need to be emotionally plugged into a game to be motivated to keep going and work hard. Repressed emotions always find a way out (which is usually not pretty).

-   **Best admired from a distance**. Take time to investigate what you’re feeling and try to work out why. Remedy what you can in the moment, but sometimes we do have to work around them or let them be and come back to them later. 

-   **Can be reinterpreted**. Nervous? Nah you’re excited and ready to go smash it. Angry? Nah it’s intensity. Go run faster, jump higher. What you think can feed back into how your body feels.

\

There’s a psychological concept called the Yerkes-Dodson law, which suggests that some level of “arousal” (not that), as in emotional engagement and excitement, is needed to perform at our best but that too much arousal is unhelpful.

-   If too low, we’re switched off, sluggish and slow to react. Try **visualisation** to get hyped again.

-   If too high, we’re ready to fly off the handle and our bodies tense up. Try **mindfulness** to calm down again.

For each athlete, the optimal level of arousal for performance is slightly different. Take time to find what is right for you.

\

**TASK**: Make a plan for how to get and keep yourself in a good state of emotional “arousal” to play your best. Include a routine before a game to find your balance and get focused, what to do when you need to get hyped, and what to do when you need to cool off.

Some ideas: 

-   **Only wear your playing kit for competitive games**: when it’s on, it’s game time. Time to show up.

-   **Listen to music**: take 5 mins before team warm-up to get in the zone, ridding your mind of distractions and focusing your body.

-   **Deep breathing**: close your eyes and check in with your body. Take 5 deep breaths. Release any tension and calm your thoughts.

-   **Tuck jumps**: fire up your muscles if they’re sleepy and dial in the explosiveness.

\

### Dealing with mistakes

Dealing with mistakes is one of the biggest threats to our mental resilience, but also one of the best ways we can develop it.

Mistakes happen. Even top players drop discs in games sometimes. 

\

Ultimate favours the team with possession - it is fairly easy to score compared to other team games like football. Any turnovers allow the opposition an opportunity to score. Teams must find a balance of retaining possession but still advancing the disc towards the endzone to score. So tournament games aren’t the best environment to try a full-pitch flick huck for the first time. But practicing throws in the park absolutely is. 

\

Be aware of your current skill level and which throws you are ready to use in a competitive game. Build up the others gradually to get to that point.

\

How to deal with mistakes

Everyone will have different strategies for this, take time to work out your own. Here’s some ideas:

1.  **Immediate defence** - As soon as the mistake happens, move on immediately and switch to defence mode.

2.  **Reflect and plan positive action** - Once you’re off the pitch, what went wrong? Do I need to make any adjustments? Then move on. Ask for help to process if needed.

3.  **Positive body language** - Stand tall, chest out, hands on hips. Body language influences our attitude. Don’t curl up and withdraw. Keep your head up.

4.  **Forgive yourself** - Your teammates already have. (They’ll soon forget it even happened.)

Other suggestions that may work for you. Handle with care:

5.  **Laugh it off** - It’s just a game. Chill. Good if you’re prone to overvalue Ultimate.

6.  **Don’t apologise** - Leave it in the past. Be in the moment. Discuss off the pitch if needed.

7.  **Have a physical outlet** - Clap. Yell. Turn anger into energy - run faster, jump higher, think sharper.

\

### Trust: Back yourself, back your teammates

Trust is earned. Trust is built through seeing people act positively over an extended period of time. 

Lack of self-trust makes for physically tense, emotionally insecure, inconsistent players. Lack of trust in a team creates tension, blame, frustration, and an imbalanced team.

\

The more we trust ourselves, the more self-confidence we’ll have, the better we’ll respond to adversity and the better we will perform. We build self-trust through confidence in our own abilities and knowing our limits. Train for ultimate, develop athletically, build your mental game. Continue to push yourself forward and gain the experience you need to perform.

\

The more we trust our teammates, the more individuals will have space to play their best and the team will have more fun and success playing together. Players will want to come back year after year. We can build this trust by:

-   **Showing that you’re grafting**: Let your team know when you’ve gone throwing or done intervals. A team that suffers together stays together. Keep pushing each other.

-   **Prioritising training and turning up on time**: Shows you care and respects everyone’s time. 

-   **Giving 100% at training**: Chase down every disc. Sprint. Bid! 

-   **Sidelining**: Be active and pay attention when you’re not on the pitch. Cheer your teammates on. 

-   **Communicating**: Be willing to talk things out when needed. Go out of your way to encourage. Be calm and willing to listen in discussions. Manage your body language carefully.

-   **Trusting your team management**: Trust each player to play the role they’ve been chosen for. If you don’t understand decisions, arrange a good time and ask.

\
