---
title: "Strength Training for Ultimate"
---

There are many ways to train for ultimate and improve athletic performance. The off season is a great time to focus on strength training while there are fewer competitive demands. Invest some time now to build a strong base for the season ahead.

### Why should I do strength training?

The primary goals are to build a body that:

-   Is more resistant to injury

-   Recovers better from intense training/games/tournaments

-   Is capable of performing athletic on-pitch movements

The last point is crucial to designing a workout program for Ultimate athletes. The focus is not to shift a lot of heavy weight, it’s to make you perform better on-field. There is a reason why most top Frisbee players do not look like olympic weightlifters. With this in mind, workouts for ultimate players tend to focus on specific muscles and movements:

-   Strong legs for powerful movement (running, jumping, turning etc)

-   Core strength for throwing and diving

-   Shoulder strength and flexibility for throwing and injury prevention

-   Strong support of knees for applying large forces at different angles when landing and changing direction (often on one leg)

-   Hip strength and mobility to improve sprint and agility technique…

-   Functional strength exercises using bodyweight or free weights rather than machines

Functional strength exercises employ multiple muscle groups through ranges of motion. If your focus is to become a better ultimate player, then your gym work should complement your on field actions. Later on, we will discuss how you can progress your S&C routine to include more power-based exercises (e.g. plyometrics). However, it is important to do some baseline strength first to avoid overloading and injury.

### Getting Started

We are giving you two different workout programs to get started. For each, there is a spreadsheet version with video links for all of the exercises and a pdf version you can print or store on your phone. You will also find the PDFs in the Spond file storage under Strength and Conditioning.

\

You should aim for at least 1 workout per week, ideally 2. 

\

**GU Introduction to strength training program:**

-   Great for anyone new to strength training or youth athletes

-   All exercises can be performed using body weight, so can be done at home

-   Focus on learning movements and light resistance rather than heavy lifts

-   2 workout days

Spreadsheet:[ https://docs.google.com/spreadsheets/d/1f2bn_1hDxToTuLL7qNfsFqCMION0gjGEChJDdLqmWt4/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1f2bn_1hDxToTuLL7qNfsFqCMION0gjGEChJDdLqmWt4/edit?usp=sharing)

PDF: <https://docs.google.com/spreadsheets/d/1f2bn_1hDxToTuLL7qNfsFqCMION0gjGEChJDdLqmWt4/edit?usp=sharing>

\

**GU S&C off-season program**

-   Requires gym equipment

-   Includes heavier compound lifts (deadlift, squats etc) to build muscle

-   3 workout days (You can rotate through these and still do 2 days a week if 3 is too many) 

Spreadsheet:[ https://docs.google.com/spreadsheets/d/1O5YESOsWenJP7_GuPA6gVbm34gF87qsga3l4L-H-WqU/edit?usp=drive_link](https://docs.google.com/spreadsheets/d/1O5YESOsWenJP7_GuPA6gVbm34gF87qsga3l4L-H-WqU/edit?usp=drive_link)

PDF:[ ](https://drive.google.com/file/d/1YdZ2z2aGX3EUHBbYIt4I0N7Chv7xakQK/view?usp=drive_link)https://drive.google.com/file/d/1umoScP4vlPoVDdVTgpVzu2w73zGG7Avq/view?usp=sharing

\

**Sets and Reps:**

-   Most of these are 3 sets of 6-8 reps

-   Rest between sets to ensure you can complete the next one (generally \~1min is fine)

-   You can choose to superset exercises (group exercises into a mini circuit) if this makes your workout more efficient. It’s up to you.

**Weight:**

-   Start light (or bodyweight) and add weight in small increments until you find the right weight for you

-   It can be useful to note down the weights you used for each exercise until you learn your own program

-   For the heavier lifts, the final rep of the final set should be difficult. If it isn’t this is a cue to increase weight next time.

-   If increasing the weight makes it too difficult to complete a set, try increasing reps by 1 or 2 first

### MIXING IT UP

We are supplying these workouts as a way to get started. You should see real benefits within 4-6 weeks with either of these programs. They should introduce you to a range of exercises and give you confidence in the gym. Over time, you may want to adapt or develop your plan. It is fine to add/remove or use alternative exercises if they work better for you. Think about:

-   Your personal goals - Which muscles need more attention for your own goals (e.g. throwing, jumping, running, rehabbing…) 

-   Your body - Are there movements you find uncomfortable or painful? What are the alternatives?

-   Your gym - What equipment is available? How busy is the gym?

-   Your time - How long do you have to workout?

We are supplying this spreadsheet with a list of additional resources for anyone interested in learning more about S&C for ultimate. This spreadsheet is editable so feel free to add your own links. We will build this up over time and discuss some of the other conditioning routines:

\

<https://docs.google.com/spreadsheets/d/1M3_td5SLFlBzHrwxY6w706WYm_sZCrkHSMS5-wXl3vE/edit?usp=sharing>

\

You will find resources online which broadly split strength training into 3 categories:

-   Strength building - Heavy weights, low reps, long rest periods

-   Hypertrophy (muscle growth) - Mid weight, mid reps

-   Muscle endurance - Light weight, high reps

If you have a particular focus then you could start to tailor your workout to these aims. For me, the biggest thing is having a program that does the basics, works within my time constraints and gives me tangible improvements in strength and mobility. Lifting heavy also comes with increased injury risk, so I wouldn’t recommend a targeted strength program without doing the base work first.

### FIND YOUR WHY

It’s important to find a routine that you enjoy and that you can maintain. At the end of the day, becoming a better ultimate player may only be one of your goals for hitting the gym. If working out is something that stimulates you, gives you more confidence or allows you to zone out from other distractions then try to maximise that. If the gym is your happy place then find the exercises you enjoy doing. If the gym is just a means to an end, then make sure your end goals are important enough to you. Feel free to freshen up your routine or try new things to stay motivated!

\

**ACTION POINTS:**

-   Fill in the spreadsheet Hannah posted:

    -   <https://docs.google.com/spreadsheets/d/11gqY8M2ra3IQ-ejJGbR947FmbWQsJhnaeV1uxHMxkqA/edit?usp=sharing>

-   Join the WhatsApp group and start sharing your workout pics:

    -   <https://chat.whatsapp.com/KteKiLSBxULJwuPZWA1osD>

-   Request a training buddy

    -   Respond to the comment below for the opt-in training partner scheme

### I NEED HELP

That’s what this group is for :) All questions are valid if you want to post on the group. Everyone is friendly and approachable, so feel free to ask advice from others. Let people know if you are going to workout and want some company. We are trying to see if it is possible to do small group sessions at a Glasgow Life gym and we will let you know more soon. You may also have trainers at your gym that can help you out.

### TRAINING PARTNERS - BUDDY SYSTEM

If you think it would be useful to have someone to chat to, motivate you or keep you accountable then please respond to the comment below. We will put people in small groups as training partners. This does not mean you need to train together. Just check in with each other every now and then and keep supporting each other.
