---
title: "How to practice your throwing skills"
---

Developing throwing skills requires focused, intentional practice. Here are some ideas and resources for practicing your skills.

### **Focused throwing sessions**

We use the term “focused throwing” to refer to drills with a deliberate emphasis on throwing skill. Adding focused throwing sessions to your training regime will help to develop your skill repertoire. You can do these at high intensity with boots to get some cardio and agility in at the same time. Choose a few drills with 1 or 2 specific aims and find some people to throw with. Here are a few example sessions:

-   GU focused throwing sessions

    -   [Phase 1: Fundamentals](https://drive.google.com/file/d/1siNHzVkC88D38arQ1dkuGW9Bhf74k3ckKjWPQBY7T5_m9iMQ75mUnj85rw458I2be3NxfaL-ONmazP3x/view?usp=sharing)

    -   [Phase 2: Dynamics](https://drive.google.com/file/d/1l422e2dpUTYWYbpOZL7sprCE2diKVny1XYay2CMdZM1r9hTxZ0El5Ztevk1ooN1_f0ExiTROsI2IfnMk/view?usp=drive_link)

    -   [Phase 3: Range](https://drive.google.com/file/d/19YsG3WTTARXm9GyRJTxsr1rtQHECkh9Ph6uIY5_CkQKKUFhqGUiYc2qHsyPLPPXjk85XuIFXs4MlcDL_/view?usp=drive_link)

-   Rowan McDonnell throwing sessions

    -   [Focused throwing session](https://www.youtube.com/watch?v=bWtWMoFx6Po&ab_channel=RowanMcDonnell)

    -   [30 min throwing session](https://www.youtube.com/watch?v=rpqT8J6BzvY&ab_channel=RowanMcDonnell)

-   Kung-fu throwing

    -   [Explanation](https://skydmagazine.com/2012/02/kung-fu-throwing/)

    -   [Checklist](https://docs.google.com/document/d/10UBznDueFkqPrsDgCz9ECGZ6kXW07fK_svnGZo6yY6o/edit?usp=sharing)

    -   [Videos](https://www.youtube.com/watch?v=5mGmnqaN3Wk)

-   Zen throwing

    -   [Explanation](https://skydmagazine.com/2011/11/wiggins-zen-throwing-routine/)

    -   [Videos](https://www.youtube.com/playlist?list=PLezzWvSJAw_Y9WqN4bE1v6EzatYqh2d0M)

### **At Training**

There is normally time to throw pre/post training or as part of the warm up. Think about how you can maximise this time (quality not quantity) by focusing your throwing and catching drills:

-   Choose something specific to work on

-   Decide if you need repetition to ingrain a skill or variation to develop the skill

-   Work on the “perfect pass”

-   Engage your brain throughout

-   Set standards (e.g. aim for zero turnovers)

These reps add up to many hours over years of practice, so think what you might be missing out on by wasting this time. There is still definitely a place for more casual throwing, especially if it helps you to zone out for a bit or experiment with your technique.

### **Indoor Season**

Playing indoors is great for skill development and a good way to invest your off-season time.

-   Fewer variables (no wind, shorter throws) makes it easier to develop technique

-   You get a lot of touches in an indoor game

-   Generally less competitive, more license to give things a go

-   If you’re ever going to throw off-hand scoobers in matches, you should probably try it indoors first!

### Plan your throwing sessions

Get the most out of your throwing sessions by planning in advance.

-   Have specific goals or drills in mind

-   What equipment do you need (discs, cones)?

-   If you are working on technique, watch a video or speak to a coach first

-   Do you need to print a plan or load it to your phone?

-   Do you need a tripod/camera setup?

-   Find good throwing partners!
